spring:
  application:
    name: myproject
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.0.218.9:3306/longi_msp_datadict?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: htf1814610808
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: 20
      # 连接池允许的最大连接数
      maximum-pool-size: 200
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
  redis:
    host: 10.0.218.9
    port: 6379
    database: 10
    password: htf1814610808
#  cloud:
#    nacos:
#      discovery:
#        # url和namespace根据实际情况修改
#        server-addr: 10.0.218.9:18888
#        namespace: d73ea4f1-3f70-40ad-8c1f-0f4c280f2e98
#      config:
#        # 配置中心地址
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        # 命名空间
#        namespace: ${spring.cloud.nacos.discovery.namespace}
#        # 配置文件格式
#        file-extension: yml
#        # 配置当前服务对应的配置文件,如果没有可以不配置
#        #name: lmsp-codegenerator-develop
#        # 分组名称
#        group: DEFAULT_GROUP
#        #refresh-enabled: true
#        # 共享配置
#        extension-configs:
#          - data-id: lmsp-common-config-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
#            group: ${spring.cloud.nacos.config.group}
#            refresh: true
server:
  port: 9070

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wk.project

logging:
  level:
    root: trace