package com.wk.project.webservice.service.impl;

import com.wk.project.webservice.service.ErpAcceptPreSalesOrdersSoapBizPtt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.2.4
 * 2023-07-13T09:25:54.052+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "ErpAcceptPreSalesOrdersSoapBiz_ptt-bindingQSService",
                  wsdlLocation = "http://soatest.longi.com:8011/ErpOmsSB/Erp/PreSalesOrders/ProxyServices/ErpAcceptPreSalesOrdersProxyService?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/ErpOmsSB/ErpAcceptPreSalesOrdersSoapBiz")
public class ErpAcceptPreSalesOrdersSoapBizPttBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/ErpOmsSB/ErpAcceptPreSalesOrdersSoapBiz", "ErpAcceptPreSalesOrdersSoapBiz_ptt-bindingQSService");
    public final static QName ErpAcceptPreSalesOrdersSoapBizPttBindingQSPort = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/ErpOmsSB/ErpAcceptPreSalesOrdersSoapBiz", "ErpAcceptPreSalesOrdersSoapBiz_ptt-bindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://soatest.longi.com:8011/ErpOmsSB/Erp/PreSalesOrders/ProxyServices/ErpAcceptPreSalesOrdersProxyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ErpAcceptPreSalesOrdersSoapBizPttBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://soatest.longi.com:8011/ErpOmsSB/Erp/PreSalesOrders/ProxyServices/ErpAcceptPreSalesOrdersProxyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ErpAcceptPreSalesOrdersSoapBizPttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ErpAcceptPreSalesOrdersSoapBizPttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErpAcceptPreSalesOrdersSoapBizPttBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ErpAcceptPreSalesOrdersSoapBizPttBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ErpAcceptPreSalesOrdersSoapBizPttBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ErpAcceptPreSalesOrdersSoapBizPttBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ErpAcceptPreSalesOrdersSoapBizPtt
     */
    @WebEndpoint(name = "ErpAcceptPreSalesOrdersSoapBiz_ptt-bindingQSPort")
    public ErpAcceptPreSalesOrdersSoapBizPtt getErpAcceptPreSalesOrdersSoapBizPttBindingQSPort() {
        return super.getPort(ErpAcceptPreSalesOrdersSoapBizPttBindingQSPort, ErpAcceptPreSalesOrdersSoapBizPtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ErpAcceptPreSalesOrdersSoapBizPtt
     */
    @WebEndpoint(name = "ErpAcceptPreSalesOrdersSoapBiz_ptt-bindingQSPort")
    public ErpAcceptPreSalesOrdersSoapBizPtt getErpAcceptPreSalesOrdersSoapBizPttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(ErpAcceptPreSalesOrdersSoapBizPttBindingQSPort, ErpAcceptPreSalesOrdersSoapBizPtt.class, features);
    }

}
