package com.wk.project.webservice.service;

import com.wk.project.webservice.info.erp.InputParameters;
import com.wk.project.webservice.info.erp.ObjectFactory;
import com.wk.project.webservice.info.erp.OutputParameters;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2023-07-13T09:25:54.012+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/ErpOmsSB/ErpAcceptPreSalesOrdersSoapBiz", name = "ErpAcceptPreSalesOrdersSoapBiz_ptt")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ErpAcceptPreSalesOrdersSoapBizPtt {

    @WebMethod(operationName = "ErpAcceptPreSalesOrdersSoapBiz", action = "ErpAcceptPreSalesOrdersSoapBiz")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/ErpAcceptPreSalesOrdersSoapBiz", partName = "OutputParameters")
    public OutputParameters erpAcceptPreSalesOrdersSoapBiz(
        @WebParam(partName = "InputParameters", name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/sp/ErpAcceptPreSalesOrdersSoapBiz")
        InputParameters inputParameters
    );
}
